/*
GenomeSequenceEncodingUtilTest for DeBruijnGenomeAssembler - an unpaired short read (~100bp) de Bruijn graph based genome assembler
Copyright (C) 2025 William Bruns

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

package org.wbdbga;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GenomeSequenceEncodingUtilTest {
    @Test
    void getDeclaredBPLength() {
        assertEquals(1, GenomeSequenceEncodingUtil.getDeclaredBPLength(new byte[]{(byte)1, (byte)0}));
        assertEquals(2, GenomeSequenceEncodingUtil.getDeclaredBPLength(new byte[]{(byte)2, (byte)0}));
        assertEquals(3, GenomeSequenceEncodingUtil.getDeclaredBPLength(new byte[]{(byte)3, (byte)0}));
        assertEquals(4, GenomeSequenceEncodingUtil.getDeclaredBPLength(new byte[]{(byte)4, (byte)0}));
        assertEquals(8, GenomeSequenceEncodingUtil.getDeclaredBPLength(new byte[]{(byte)8, (byte)0b11100100, (byte)0b11100100}));
    }

    @Test 
    void getStringFromBPBytes() {
        // reads are encoded with 4 base pairs per byte, with first byte giving the length of the read
        // after that two bits per base pair are used only
        // that means e.g. that the same 0 byte at the end can be e.g. "A", "AA", "AAA", or "AAAA" depending on the first byte indicating the length
        assertEquals("A", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)1, (byte)0}));
        assertEquals("AA", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)2, (byte)0}));
        assertEquals("AAA", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)3, (byte)0}));
        assertEquals("AAAA", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)4, (byte)0}));

        // zero padded as generated by our encoder (see inverse of this in getBPBytesFromString test)
        assertEquals("A", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)1, (byte)0b00000000}));
        assertEquals("AC", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)2, (byte)0b00000100}));
        assertEquals("ACG", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)3, (byte)0b00100100}));
        assertEquals("ACGT", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)4, (byte)0b11100100}));

        // can handle truncated as well (bits set outside the valid region; no corresponding inverse test)
        assertEquals("A", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)1, (byte)0b11100100}));
        assertEquals("AC", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)2, (byte)0b11100100}));
        assertEquals("ACG", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)3, (byte)0b11100100}));
        assertEquals("ACGT", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)4, (byte)0b11100100}));

        assertEquals("ACGTACGT", GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{(byte)8, (byte)0b11100100, (byte)0b11100100}));
    }

    @Test
    public void getStringFromBPBytesThrowsExceptionIfFirstByteIndicatesMoreBPsThanCouldFitInArray() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
                String out = GenomeSequenceEncodingUtil.getStringFromBPBytes(new byte[]{5,0});
            });
        assertEquals("Malformed BP bytes array: first byte indicates a number of base pairs that could not fit in the array provided", exception.getMessage());
    }

    @Test
    public void getBPBytesFromString() {
        // need to use assertArrayEquals here, not assertEquals
        assertArrayEquals(new byte[]{(byte)1, (byte)0}, GenomeSequenceEncodingUtil.getBPBytesFromString("A"));
        assertArrayEquals(new byte[]{(byte)2, (byte)0}, GenomeSequenceEncodingUtil.getBPBytesFromString("AA"));
        assertArrayEquals(new byte[]{(byte)3, (byte)0}, GenomeSequenceEncodingUtil.getBPBytesFromString("AAA"));
        assertArrayEquals(new byte[]{(byte)4, (byte)0}, GenomeSequenceEncodingUtil.getBPBytesFromString("AAAA"));

        // note not an inversion of the other test since I flipped bits outside the length which would normally be set to zero by the encoder in the decoding test
        assertArrayEquals(new byte[]{(byte)1, (byte)0b00000000}, GenomeSequenceEncodingUtil.getBPBytesFromString("A"));
        assertArrayEquals(new byte[]{(byte)2, (byte)0b00000100}, GenomeSequenceEncodingUtil.getBPBytesFromString("AC"));
        assertArrayEquals(new byte[]{(byte)3, (byte)0b00100100}, GenomeSequenceEncodingUtil.getBPBytesFromString("ACG"));
        assertArrayEquals(new byte[]{(byte)4, (byte)0b11100100}, GenomeSequenceEncodingUtil.getBPBytesFromString("ACGT"));

        assertArrayEquals(new byte[]{(byte)8, (byte)0b11100100, (byte)0b11100100}, GenomeSequenceEncodingUtil.getBPBytesFromString("ACGTACGT"));
    }

    @Test
    public void getBPBytesFromStringThrowsInvalidCharacterInBPStringException() {
        GenomeSequenceEncodingUtil.InvalidCharacterInBPStringException exception = assertThrows(GenomeSequenceEncodingUtil.InvalidCharacterInBPStringException.class, () -> {
                byte[] bpBytes = GenomeSequenceEncodingUtil.getBPBytesFromString("ACTGF");
            });
        assertEquals("Unexpected character 'F', must be one of 'A','C','G','T'", exception.getMessage());
    }

    @Test
    public void getBPBytesFromStringThrowsTooLongBPReadStringToEncodeUsingBPBytesFromStringException() {
        // 255 length should be ok
        String aTimes255 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
        GenomeSequenceEncodingUtil.getBPBytesFromString(aTimes255);

        // but 256 should trigger an Exception
        GenomeSequenceEncodingUtil.TooLongBPReadStringToEncodeUsingBPBytesFromStringException exception = assertThrows(GenomeSequenceEncodingUtil.TooLongBPReadStringToEncodeUsingBPBytesFromStringException.class, () -> {
                byte[] bpBytes = GenomeSequenceEncodingUtil.getBPBytesFromString(aTimes255 + "A");
            });
        assertEquals("getBPBytesFromString is intended to encode reads (usually 100bp or so) and kmers (shorter than reads) and so currently only supports individual strings up to 255 bases long.", exception.getMessage());
    }

    @Test
    void get4ByteRepresentationForReadIndexAndWithinReadIndex() {
        assertArrayEquals(new byte[]{(byte)0b01000000, (byte)0, (byte)0, (byte)0b00100000}, GenomeSequenceEncodingUtil.get4ByteRepresentationForReadIndexAndWithinReadIndex(64, 32));
    }

    @Test
    void get4ByteRepresentationForReadIndexAndWithinReadIndexThrowsReadIndexOutOfSupportedRangeFor4ByteSequenceInReadReferenceEncoding() {
        // (1 << 24) - 1 should be ok
        GenomeSequenceEncodingUtil.get4ByteRepresentationForReadIndexAndWithinReadIndex((1 << 24) - 1, 32);

        // but read index of (1 << 24) should trigger an exception
        GenomeSequenceEncodingUtil.ReadIndexOutOfSupportedRangeFor4ByteSequenceInReadReferenceEncoding exception = assertThrows(GenomeSequenceEncodingUtil.ReadIndexOutOfSupportedRangeFor4ByteSequenceInReadReferenceEncoding.class, () -> {
                GenomeSequenceEncodingUtil.get4ByteRepresentationForReadIndexAndWithinReadIndex((1 << 24), 32);
            });
        assertEquals("get4ByteRepresentationForReadIndexAndWithinReadIndex only supports non-negative read indices, and since 3 byte encoding for read index is used, 2^24 reads is the maximum", exception.getMessage());
    }

    @Test
    void get4ByteRepresentationForReadIndexAndWithinReadIndexThrowsWithinReadIndexOutOfSupportedRangeFor4ByteSequenceInReadReferenceEncoding() {
        // 255 should be ok
        GenomeSequenceEncodingUtil.get4ByteRepresentationForReadIndexAndWithinReadIndex((1 << 24) - 1, 255);

        // but within read index of 256 should trigger an Exception
        GenomeSequenceEncodingUtil.WithinReadIndexOutOfSupportedRangeFor4ByteSequenceInReadReferenceEncoding exception = assertThrows(GenomeSequenceEncodingUtil.WithinReadIndexOutOfSupportedRangeFor4ByteSequenceInReadReferenceEncoding.class, () -> {
                GenomeSequenceEncodingUtil.get4ByteRepresentationForReadIndexAndWithinReadIndex((1 << 24) - 1, 256);
            });
        assertEquals("get4ByteRepresentationForReadIndexAndWithinReadIndex only supports non-negative within read indices, and since 1 byte encoding for the within read index is used, only 0-255 is supported for within read (consistent with getBPBytesFromString which only encodes up to 255 base long reads)", exception.getMessage());
    }

    @Test
    void getReadIndexAndWithinReadIndexFrom4ByteRepresentation() {
        assertArrayEquals(new int[]{64, 32}, GenomeSequenceEncodingUtil.getReadIndexAndWithinReadIndexFrom4ByteRepresentation(new byte[]{(byte)0b01000000, (byte)0, (byte)0, (byte)0b00100000}));
    }

    @Test
    void decodeKmerBytesToIntArray() {
        assertArrayEquals(new int[]{64, 32}, GenomeSequenceEncodingUtil.decodeKmerBytesToIntArray(new byte[]{(byte)0b01000000, (byte)0, (byte)0, (byte)0b00100000}));
    }

    @Test
    void decodeKmerBytesToIntArrayThrowsExceptionIfTheNumberOfBytesIsNot4() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
                GenomeSequenceEncodingUtil.decodeKmerBytesToIntArray(new byte[]{(byte)0b01000000, (byte)0, (byte)0, (byte)0b00100000, (byte)0});
            });
        assertEquals("Paired reads or other usecases for kmer bytes of length 5 or otherwise not length 4 are not currently supported!", exception.getMessage());
    }
}
